# Generated by Django 3.2.6 on 2021-08-05 11:09

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Accueil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('resu', models.TextField(null=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_miseajour', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(max_length=60, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.categorie')),
            ],
        ),
    ]
